# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pTdZ8Tvn7GUagkIRS-qTEXiwV-Mn_NY8
"""

import matplotlib.pyplot as plt

# Data from the C code output (times taken for each algorithm)
# These are the example times. Replace with actual timings you get from running the C code.
algorithms = ['Bellman-Ford', 'Dijkstra']
times_taken = [0.0008, 0.0002]  # Example times in seconds, modify based on actual output

# Create a bar chart comparing the time taken by both algorithms
plt.figure(figsize=(8, 6))

plt.bar(algorithms, times_taken, color=['lightblue', 'lightcoral'])

# Adding titles and labels
plt.title('Performance Comparison: Bellman-Ford vs Dijkstra', fontsize=14)
plt.xlabel('Algorithm', fontsize=12)
plt.ylabel('Time Taken (seconds)', fontsize=12)

# Display the values on top of the bars
for i, v in enumerate(times_taken):
    plt.text(i, v + 0.00005, f"{v:.4f}", ha='center', va='bottom', fontsize=12)

# Show gridlines and make the plot more readable
plt.grid(axis='y', linestyle='--', alpha=0.7)

# Show the plot
plt.tight_layout()
plt.show()